version: '3.5'

services:
  client-app:
    container_name: monitor-client
    build:
      context: client
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - server-app
    env_file:
      - .env
    ports:
      - '8080:80'
    networks:
      - app-network

  server-app:
    container_name: monitor-server
    build:
      context: server
      dockerfile: Dockerfile
      args:
        ENV: 'development'
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '9090:80'
    volumes:
      - ./server:/app
      - ./server/Docker/usr/.gemrc:/root/.gemrc
    networks:
      - app-network

  db:
    image: postgres:12.2-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-volume:

networks:
  app-network:
    driver: bridge
